### ISSUE TITLE
Unable to connect to AVD and My phone when trying to run using F5

### ISSUE THREAD

**Issue by SubhanRaj** [iampawan/30DaysOfFlutter#18]
# I have already opened the original issues here on Flutter's official Github Issues page, but as I'm doing **30 Days of Flutter** , I thought that I should share my issue here to.

## Anyone can please check the original issue here - [https://github.com/flutter/flutter/issues/82411](url)

@iampawan @arps18

**Comment by 11223345** [comment]
Try using lower resolution

**Comment by SubhanRaj** [comment]
I'm able to solve this
All I had to do, is manually uninstall and install Studio and SDK
Orginal One is also closed
And I'm Closing this one too.
Check the original one here : [https://github.com/flutter/flutter/issues/82411](https://github.com/flutter/flutter/issues/82411 )
