### ISSUE TITLE
Issues with VxBuilder

### ISSUE THREAD

**Issue by xanyl** [iampawan/30DaysOfFlutter#36]
```
VxBuilder(
            mutations: {RemoveMutation},
            builder: (context) {
              return "\$${_cart.totalPrice}"
                  .text
                  .xl5
                  .color(context.theme.accentColor)
                  .make();
            },
)
```
          
![Screenshot 2022-05-24 083155](https://user-images.githubusercontent.com/59596981/169938516-e9832c8c-bdcc-4b2d-95bc-db934464c3b6.png)
)

**error messege**:   _The argument type 'Widget Function(BuildContext)' can't be assigned to the parameter type 'Widget Function(BuildContext, dynamic, VxStatus?)'.dart[argument_type_not_assignable](https://dart.dev/diagnostics/argument_type_not_assignable)_

**Comment by rohantraining** [comment]
> ```
> VxBuilder(
>             mutations: {RemoveMutation},
>             builder: (context) {
>               return "\$${_cart.totalPrice}"
>                   .text
>                   .xl5
>                   .color(context.theme.accentColor)
>                   .make();
>             },
> )
> ```
> 
> ![Screenshot 2022-05-24 083155](https://user-images.githubusercontent.com/59596981/169938516-e9832c8c-bdcc-4b2d-95bc-db934464c3b6.png) )
> 
> **error messege**: _The argument type 'Widget Function(BuildContext)' can't be assigned to the parameter type 'Widget Function(BuildContext, dynamic, VxStatus?)'.dart[argument_type_not_assignable](https://dart.dev/diagnostics/argument_type_not_assignable)_

how did u solve Vxbuilder issue?

**Comment by rohantraining** [comment]
> ```
> VxBuilder(
>             mutations: {RemoveMutation},
>             builder: (context) {
>               return "\$${_cart.totalPrice}"
>                   .text
>                   .xl5
>                   .color(context.theme.accentColor)
>                   .make();
>             },
> )
> ```
> 
> ![Screenshot 2022-05-24 083155](https://user-images.githubusercontent.com/59596981/169938516-e9832c8c-bdcc-4b2d-95bc-db934464c3b6.png) )
> 
> **error messege**: _The argument type 'Widget Function(BuildContext)' can't be assigned to the parameter type 'Widget Function(BuildContext, dynamic, VxStatus?)'.dart[argument_type_not_assignable](https://dart.dev/diagnostics/argument_type_not_assignable)_

how did u solve vxbuilder issue?

**Comment by rohantraining** [comment]
Plzz tell me how do I resolve vxbuilder issue?
